### ISSUE TITLE
Drasil questions -  Time point

### ISSUE THREAD

**Issue by muralidn** [muralidn/Drasil#1]
@oluowoj @smiths

For my program, I need to get the current system time, for example, an equivalent of `time.time() `in Python. I think Drasil does not have that feature now.

I wonder if Drasil can interface with external libraries? I saw a few CPP files in the NoPCM project. If not any pointers to how I can quickly add support for it?

**Comment by smiths** [comment]
Yes, Drasil can interface with external libraries, but I'm not sure how easy this would be.  We can ask Dr. Carette if this is necessary.  The first question though is whether this is necessary.  Why do you need the current time?  I've been assuming all along that you are doing a simulation, likely starting at time zero and running until the stopping time.  Can you do it this way?  I know you have goals related to solving for the time, but I feel like you can drop this goal.  Since you are using a time stepping algorithm for the ODE, you can always deduce the time by knowing the time step size and the index in the sequence of the solutions.

**Comment by muralidn** [comment]
Thanks for the response Dr. @smiths. 

This is no longer an issue as the IM is resolved into an ODE (see #2).
